In [9]:
import numpy as np
import pandas as pd

In [10]:
!pip install netCDF4

Requirement already satisfied: netCDF4 in /usr/local/lib/python3.10/dist-packages (1.6.4)
Requirement already satisfied: cftime in /usr/local/lib/python3.10/dist-packages (from netCDF4) (1.6.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from netCDF4) (2023.7.22)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from netCDF4) (1.23.5)

In [11]:
!pip install xarray

Requirement already satisfied: xarray in /usr/local/lib/python3.10/dist-packages (2023.7.0)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.10/dist-packages (from xarray) (1.23.5)
Requirement already satisfied: pandas>=1.4 in /usr/local/lib/python3.10/dist-packages (from xarray) (1.5.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from xarray) (23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4->xarray) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4->xarray) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.4->xarray) (1.16.0)

In [12]:
import netCDF4 as nc
import xarray as xr

In [18]:
ds_eastern_sst1 = xr.open_dataset('/content/Eastern_SST.nc')

target_latitude = 5.25
target_longitude = 99.75

ds_eastern_sst2 = ds_eastern_sst1.sel(latitude = target_latitude, longitude = target_longitude, method = 'nearest')

ds_eastern_sst3 = ds_eastern_sst2.reduce(np.nansum, dim='expver',keep_attrs=True)

df_eastern_sst = ds_eastern_sst3.to_dataframe()
df_eastern_sst

            longitude  latitude         sst
time
1940-01-01      99.75      5.25  301.730255
1940-02-01      99.75      5.25  302.175781
1940-03-01      99.75      5.25  302.489716
1940-04-01      99.75      5.25  303.593964
1940-05-01      99.75      5.25  303.596191
...               ...       ...         ...
2023-05-01      99.75      5.25  303.916992
2023-06-01      99.75      5.25  303.923584
2023-07-01      99.75      5.25  303.803955
2023-08-01      99.75      5.25  303.635223
2023-09-01      99.75      5.25  303.232910

[1005 rows x 3 columns]

In [19]:
df_eastern_sst.to_excel('Eastern_SST.xlsx', index=True)

In [20]:
ds_western_sst1 = xr.open_dataset('/content/Western_SST.nc')

target_latitude = 10.25
target_longitude = 59.75

ds_western_sst2 = ds_western_sst1.sel(latitude = target_latitude, longitude = target_longitude, method = 'nearest')

ds_western_sst3 = ds_western_sst2.reduce(np.nansum, dim='expver',keep_attrs=True)

df_western_sst = ds_western_sst3.to_dataframe()
df_western_sst

            longitude  latitude         sst
time
1940-01-01      59.75     10.25  299.468475
1940-02-01      59.75     10.25  300.249054
1940-03-01      59.75     10.25  300.388184
1940-04-01      59.75     10.25  302.095947
1940-05-01      59.75     10.25  303.119598
...               ...       ...         ...
2023-05-01      59.75     10.25  303.642639
2023-06-01      59.75     10.25  302.099365
2023-07-01      59.75     10.25  300.484650
2023-08-01      59.75     10.25  300.856995
2023-09-01      59.75     10.25  301.211426

[1005 rows x 3 columns]

In [21]:
df_western_sst.to_excel('Western_SST.xlsx', index=True)

In [22]:
import csv

soi_data = []

with open('/content/SOI_text_data.txt', 'r') as file:
    lines = file.readlines()
    for line in lines:
        values = line.strip().split()
        soi_data.append(values)

with open('SOI.csv', 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    for row in soi_data:
        csvwriter.writerow(row)

soi_df = pd.read_csv('/content/SOI.csv')

soi_df.to_excel("SOI.xlsx", index=False)

In [23]:
import csv

noa_data = []

with open('/content/NOA_data.txt', 'r') as file:
    lines = file.readlines()
    for line in lines:
        values = line.strip().split()
        noa_data.append(values)

with open('NOA.csv', 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    for row in noa_data:
        csvwriter.writerow(row)

noa_df = pd.read_csv('/content/NOA.csv')

noa_df.to_excel("NOA.xlsx", index=False)

In [24]:
import csv

pdo_data = []

with open('/content/PDO_data.txt', 'r') as file:
    lines = file.readlines()
    for line in lines:
        values = line.strip().split()
        pdo_data.append(values)

with open('PDO.csv', 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    for row in pdo_data:
        csvwriter.writerow(row)

pdo_df = pd.read_csv('/content/PDO.csv')

pdo_df.to_excel("PDO.xlsx", index=False)